eos:
  person-conversion:
    mode: automatic #conversion for composition conversion
  visit-conversion:
    aql: SELECT e/ehr_id/value as ehr_id, c/context/other_context/items[openEHR-EHR-CLUSTER.case_identification.v0]/items[at0001]/value/value as source_id, c/content[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0]/data[at0001]/items[at0004]/value/value as begin, c/content[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0]/data[at0001]/items[at0005]/value/value as end FROM EHR e CONTAINS COMPOSITION c WHERE c/archetype_details/template_id/value='Patientenaufenthalt'
  cdm:
    database-name: postgres
    schema: &schema public       # the &schema needs to stay when modifying the value
  eras-period-cron:
    enabled: false               # default false
  #  cron: "0 0 */2 * * ?"        # every two hours
  openehr:
    base-url: http://localhost:8080/ehrbase/
    security:
      type: basic
      user:
        name: myuser
        password: myPassword432

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always

spring:
  jpa:
   # show-sql: true
    properties:
      hibernate:
        default_schema: *schema
        hibernate.ddl-auto: update
        order_inserts: true
        jdbc:
          batch_size:  1000

  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  file:
    name: ./logs/omopbridge.log
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    root: info
    org:
      springframework:
        boot: error
        nodeValue: error
      hibernate:
        type:
          descriptor:
            sql:
              basicbinder: TRACE
  logback:
    rollingpolicy:
      max-history: '20'
      max-file-size: 100MB




