#docker-compose-eos+cdm.yml
#https://github.com/docker-library/postgres/issues/146
services:
  cdm-db:
    image: cdm_db:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - eos-net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h localhost"
      interval: 10s
      timeout: 5s
      retries: 70

  eos:
    image: ghcr.io/sevkohler/eos:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cdm-db:5432/postgres
    ports:
      - "8081:8081"
    depends_on:
      cdm-db:
        condition: service_healthy
    networks:
      - eos-net

networks:
  eos-net: {}
