#docker-compose-eos+cdm.yml
#https://github.com/docker-library/postgres/issues/146
services:
  cdm-db:
    image: cdm_db:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    #  expose:
    #    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    healthcheck:
      test: "pg_isready -q -h localhost"
      interval: 10s
      timeout: 5s
      retries: 70

  eos:
    image: ghcr.io/sevkohler/eos:latest
    volumes:
      - ../src/main/resources/application.yml:/workspace/BOOT-INF/classes/application.yml
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/postgres
    ports:
      - "8081:8081"
    depends_on:
      cdm-db:
        condition: service_healthy
    network_mode: "host"